### ISSUE TITLE
感谢提供whois-servers.txt

### ISSUE THREAD

**Issue by mouday** [WooMai/whois-servers#1]
我的项目引用了你的项目文件：https://github.com/WooMai/whois-servers/blob/master/list.txt

项目地址

https://github.com/mouday/domain-admin

**Comment by WooMai** [comment]
感谢支持，目前添加了自动化更新，如果有需要可以同步下~

**Comment by mouday** [comment]
好的，谢谢

**Comment by mouday** [comment]
发现你的这个文件更新挺及时，我的项目没有及时更新，所以有些域名查不到信息
